---
- name: Disable other firewalls
  when: firewall_disable_firewalld or firewall_disable_ufw
  ansible.builtin.include_tasks: "{{ task_file }}"
  with_first_found:
    - "noauto_disable_other_fw_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "noauto_disable_other_fw_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "noauto_disable_other_fw_{{ ansible_distribution }}.yml"
    - "noauto_disable_other_fw_{{ ansible_os_family }}.yml"
    - "noauto_disable_other_fw_{{ ansible_lsb.id }}.yml"
  loop_control:
    loop_var: task_file
