---
- name: Disable the ufw firewall
  when: iptables_disable_ufw
  block:
    - name: Check if ufw package is installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Disable the ufw firewall
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false
      when: "'ufw' in ansible_facts.packages"
